import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import prisma from "@/lib/db";
import { Layers, Activity, Star, Users, Briefcase } from "lucide-react";
import ReferralLinkCard from "@/components/referral/ReferralLinkCard";

export default async function ReferralPage() {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");

  const user = await prisma.user.findUnique({
    where: { id: session.user.id },
    include: {
      referralsMade: {
        include: { referee: true }
      },
      referralEarnings: true
    }
  });

  if (!user) redirect("/login");

  const headersList = await headers();
  const host = headersList.get("host") || "";
  const protocol = host.includes("localhost") ? "http" : "https";
  const origin = `${protocol}://${host}`;
  const referralLink = `${origin}/register/${user.id}`;

  const totalCommissions = user.referralEarnings.reduce((acc, curr) => acc + curr.commission, 0);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <header>
        <h1 className="text-3xl font-black text-white mb-2 tracking-tight">Affiliate Protocol</h1>
        <p className="text-[var(--text-secondary)] font-medium">Expand the MINE$ network and earn 5% lifecycle protocol credits on all yield generated by your referred validators.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

        {/* Link Card */}
        <div className="bg-[var(--surface-800)] border border-[var(--surface-600)] rounded-[32px] p-8 relative shadow-2xl overflow-hidden card-lift">
          <div className="flex items-center gap-4 mb-6">
            <div className="p-3 bg-white/5 rounded-2xl border border-white/5">
              <Layers size={22} className="text-[var(--color-accent)]" />
            </div>
            <h3 className="text-xl font-black text-white tracking-tight uppercase">Protocol Entry Link</h3>
          </div>
          <p className="text-[var(--text-muted)] text-xs font-medium mb-6 leading-relaxed uppercase tracking-widest opacity-70">Share your unique node-identifier. New validators registering through this link will be synchronized with your affiliate cluster.</p>

          <div className="relative z-10">
            <ReferralLinkCard referralLink={referralLink} />
          </div>
        </div>

        {/* Commission Stats */}
        <div className="bg-gradient-to-br from-[var(--surface-800)] to-indigo-500/10 border border-white/5 rounded-[32px] p-8 relative shadow-2xl overflow-hidden card-lift group">
          <div className="absolute top-0 right-0 p-8 opacity-[0.05] group-hover:scale-110 transition-transform">
            <Star size={100} className="text-[var(--color-accent)]" />
          </div>

          <h3 className="text-[var(--text-muted)] text-[10px] font-black uppercase tracking-[0.2em] mb-4 opacity-80">Aggregate Protocol Credits</h3>
          <div className="text-5xl font-black text-[var(--color-accent)] mono-figure tracking-tighter my-2">
            ₦ {totalCommissions.toLocaleString(undefined, { minimumFractionDigits: 2 })}
          </div>
          <div className="mt-8 flex items-center gap-3 py-2 px-4 bg-black/30 rounded-full border border-white/5 w-fit">
            <Activity size={14} className="text-green-500 animate-pulse" />
            <span className="text-[10px] text-green-500 font-black uppercase tracking-widest">Synced & Reconciled Daily</span>
          </div>
        </div>
      </div>

      {/* Downline Table */}
      <div className="bg-[var(--surface-800)] border border-[var(--surface-600)] rounded-[32px] overflow-hidden mt-8 shadow-xl">
        <div className="p-8 border-b border-white/5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Users size={20} className="text-[var(--color-accent)]" />
            <h3 className="text-lg font-black text-white tracking-tight uppercase">Synchronized Nodes ({user.referralsMade.length})</h3>
          </div>
          <div className="px-3 py-1 bg-white/5 rounded text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest leading-none">Global Cluster Data</div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-[var(--text-secondary)]">
            <thead className="bg-black/20 text-[var(--text-muted)] uppercase tracking-[0.2em] text-[10px] font-black border-b border-white/5">
              <tr>
                <th className="px-8 py-5">Validator Node</th>
                <th className="px-8 py-5">Tier Status</th>
                <th className="px-8 py-5">Synchronization Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {user.referralsMade.length === 0 ? (
                <tr>
                  <td colSpan={3} className="px-8 py-16 text-center text-[var(--text-muted)]">
                    <div className="flex flex-col items-center">
                      <Briefcase size={32} className="opacity-10 mb-4" />
                      <p className="text-xs font-bold uppercase tracking-widest italic">No validator nodes currently synchronized</p>
                    </div>
                  </td>
                </tr>
              ) : (
                user.referralsMade.map((ref) => (
                  <tr key={ref.id} className="hover:bg-white/[0.02] transition-colors group">
                    <td className="px-8 py-5 font-bold text-white group-hover:text-[var(--color-accent)] transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-white/5 rounded-lg flex items-center justify-center border border-white/5 group-hover:border-[var(--color-accent)]/20">
                          <span className="text-[10px] font-black">{ref.referee.name.charAt(0)}</span>
                        </div>
                        {ref.referee.name}
                      </div>
                    </td>
                    <td className="px-8 py-5">
                      <span className={`px-3 py-1 text-[9px] font-black rounded-lg uppercase tracking-widest shadow-lg ${ref.referee.plan === 'PREMIUM' ? 'bg-[var(--color-accent)] text-[#0a0f0d]' : 'bg-white/5 text-white border border-white/5'
                        }`}>
                        {ref.referee.plan} NODE
                      </span>
                    </td>
                    <td className="px-8 py-5 font-mono text-[11px] font-bold opacity-60 group-hover:opacity-100">{ref.createdAt.toLocaleDateString()}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
