version: "3.9"
services:
  postgres:
    build: .
    restart: always
    environment:
      POSTGRES_DB: mines_db
      POSTGRES_USER: mines_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
